### ISSUE TITLE
Obsolete links instead of https://jenkins-wiki-exporter.jenkins.io/?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/jenkins-wiki-exporter#24]
Should we change the official location to https://jenkins-wiki-exporter.jenkins.io/ ?

**Comment by halkeye** [comment]
I think so. Where are you still seeing the old one? Docs maybe?

**Comment by oleg-nenashev** [comment]
README of this repo + jenkins.io docs. Can fix all the stuff

**Comment by halkeye** [comment]
Oh yea, and the header too, I couldn't update that after the fork

**Comment by halkeye** [comment]
Okay, settings bot is enabled, so I was able to change everything but jenkins.io

\o/ /o\

**Comment by oleg-nenashev** [comment]
Created https://github.com/jenkins-infra/jenkins.io/pull/2651

**Comment by oleg-nenashev** [comment]
Fixed
