### ISSUE TITLE
Status dashboard: Some statuses are not correct

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/jenkins-wiki-exporter#30]
Hi @halkeye @zbynek . It looks like the service prints "TODO" for the plugins which have already got migration pull requests if these PRs were merged but not released. E.g. https://github.com/jenkinsci/ownership-plugin/pull/78

From what I see in https://github.com/jenkins-infra/jenkins-wiki-exporter/pull/25 , there "Pull" field just uses the constant and does not poll GitHub.

What if we query https://github.com/search?q=org%3Ajenkinsci+%22plugins.jenkins.io%22+%22documentation%22+is%3Apr&type=Issues and use this data as a source? I can probably write a Jenkins job which would generate the data automagically

**Comment by zbynek** [comment]
Yep, currently the PR list needs to be maintained manually, making it automatic would be cool. How to easily detect relevant PRs is not clear to me (checking just title is not reliable,, checking content of PR may need too much effort).

**Comment by zbynek** [comment]
@oleg-nenashev can this be closed now or do you want to keep it for adding the merged/pending distinction?
