### ISSUE TITLE
Hosting the Docker image in the https://hub.docker.com/u/jenkinsinfra org?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/jenkins-wiki-exporter#32]
@halkeye @olblak Would it make sense to reconfigure the image build process so that we get the image hosted on https://hub.docker.com/u/jenkinsinfra where we host all other Infra images? It could be a DockerHub autobuild or a Trusted CI build

**Comment by halkeye** [comment]
Sounds good to me

**Comment by olblak** [comment]
If you want to publish it from jenkins-infra, just use  'infra.withDockerCredentials` like [here](https://github.com/jenkins-infra/openvpn/blob/staging/Jenkinsfile#L54-L37) from the Jenkinsfile
Then I'll have to create a new job on trusted.ci, and also on Dockerhub
