### ISSUE TITLE
Add support of exporting pages by URL

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/jenkins-wiki-exporter#5]
#4 reveals some discovery issues. Also, we cannot export non-plugin documentation in such way, and we also want to move Wiki pages to jenkins.io easier than in https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#moving-documentation-from-jenkins-wiki. 

It would be great if there was just a way to specify URL for export. After that we would need to somehow convert URL to a Confluence Page ID so that we can use HTML export API. There is no good REST API for URL->pageID conversion it as I discovered, but we can just download and parse the Wiki page from URL to extract ID

CC @timja

**Comment by halkeye** [comment]
https://confluence.atlassian.com/confkb/how-to-get-confluence-page-id-648380445.html if not url but page id then this is easy

**Comment by halkeye** [comment]
And its not hard to get the page id! exciting https://community.atlassian.com/t5/Confluence-questions/Identify-page-from-URL/qaq-p/742455

(you kinda found it too, but links++)

**Comment by halkeye** [comment]
Okay also need to port https://github.com/jenkins-infra/plugin-site-api/blob/abcc418f5b8094f8794bb6653077614612fae076/src/main/java/io/jenkins/plugins/services/impl/ConfluenceDirectExtractor.java#L38-L58

**Comment by halkeye** [comment]
98% done, see #5

Just didn't handle stripping out the old content like the plugin api does

**Comment by oleg-nenashev** [comment]
Should we close it and create a follow-up?

**Comment by halkeye** [comment]
👍
