### ISSUE TITLE
External-links keep showing up in exported  files.

### ISSUE THREAD

**Issue by sladyn98** [jenkins-infra/jenkins-wiki-exporter#53]
`{.external-links}`  keep showing up in the exported docs along with confluence embedded links.These have to be removed in every PR that is made for migration. 
Guess we can get rid of it before export

**Comment by halkeye** [comment]
good idea

**Comment by sladyn98** [comment]
https://github.com/jenkins-infra/jenkins-wiki-exporter/blob/a3f42601f966f5d22fed4146551f06d73bf9eac3/utils.js#L59

Is this the line responsible to get all the images. Because most of the external links turn up in the image links.So I was wondering if parsing the string and getting rid of the trailing link would be a good idea thoughts

CC @timja

**Comment by halkeye** [comment]
yea, it finds all `<img` tags in the html and returns it. Does that for downloading I believe.

**Comment by timja** [comment]
possibly might be better to update it here:
https://github.com/jenkins-infra/jenkins-wiki-exporter/blob/a3f42601f966f5d22fed4146551f06d73bf9eac3/index.js#L129

**Comment by halkeye** [comment]
I'm confused, I thought the issue was a class .external-links kept showing up.
Whats the actual problem? its downloading extra files?

**Comment by timja** [comment]
> I'm confused, I thought the issue was a class .external-links kept showing up.
> Whats the actual problem? its downloading extra files?

It's some extra 'plain' text being added to the markdown
`image markdown content`{.external-links}

**Comment by halkeye** [comment]
yea, thats a tricky one.

With cheerio (server side jquery) you could just do $('.external-links').removeClass('external-links') before it gets processed.

**Comment by sladyn98** [comment]
> yea, thats a tricky one.
> 
> With cheerio (server side jquery) you could just do $('.external-links').removeClass('external-links') before it gets processed.

I am not much experienced with chererio but I could give it a shot in a PR

**Comment by sladyn98** [comment]
Closed via : https://github.com/jenkins-infra/jenkins-wiki-exporter/pull/55
