### ISSUE TITLE
Parser, that collects wiki-pages, except plugin-wiki-pages

### ISSUE THREAD

**Issue by Yunir** [jenkins-infra/jenkins-wiki-exporter#67]
Here is a parser that collects all the wiki-pages, that were found by confluence searchv3 REST API, and excludes links to plugins (using the [plugin-documentation-urls.json](https://updates.jenkins.io/current/plugin-documentation-urls.json) list) and URLs, ending with `display/JENKINS/*+Plugin`:
```python
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 31 18:07:06 2020

@author: yunir
"""

import requests

# collect all parsed plugins-pages urls
plugins_urls_list = []
plugins_dict = requests.get("https://updates.jenkins.io/current/plugin-documentation-urls.json").json()
for key in plugins_dict:
    if 'url' in plugins_dict[key].keys():
        plugins_urls_list.append(plugins_dict[key]['url'].split('/')[-1])

# collect all wiki-pages urls except plugin-pages and save it to json 
pages_urls_dict = {}
not_found_plugin_urls_dict = {}
spaces = requests.get('https://wiki.jenkins.io/rest/api/space?expand=homepage&type=global').json()
for space in spaces['results']:
    space_key = space['key']
    start=0
    while True:
        pages = requests.get('https://wiki.jenkins.io/rest/searchv3/1.0/search?type=page&where={0}&startIndex={1}'.format(space_key, start)).json()
        results = pages['results']
        for page in results:
            url = page['url'].split('?')[0]
            if url.split('/')[-1] in plugins_urls_list:
                continue
            url = 'https://wiki.jenkins.io{0}'.format(url)
            title = page['title']
            if url.split('+')[-1].lower() == 'plugin':
                not_found_plugin_urls_dict[title] = {"url":url}
            else:
                pages_urls_dict[title] = {"url":url}
        start+=10

        if start > pages['total']:
            break     

with open('wiki-pages-urls.json', 'w', encoding='utf-8') as dump_file:
    dump_file.write(str(pages_urls_dict))

with open('check-manually-pages-urls.json', 'w', encoding='utf-8') as dump_file:
    dump_file.write(str(not_found_plugin_urls_dict))
```
### Generated files
* [wiki-pages-urls.json.txt](https://github.com/jenkins-infra/jenkins-wiki-exporter/files/4176727/wiki-pages-urls.json.txt)
* [check-manually-pages-urls.json.txt](https://github.com/jenkins-infra/jenkins-wiki-exporter/files/4176729/check-manually-pages-urls.json.txt)

Add `*.txt`, because github-issues refuse adding `*.json` files.

### Warning
I generate [check-manually-pages-urls.json.txt](https://github.com/jenkins-infra/jenkins-wiki-exporter/files/4176729/check-manually-pages-urls.json.txt) too, because there may face non-plugin wiki-pages, but ended with `display/JENKINS/*+Plugin` URL too.
Example: 
* [Convert standard mail notifications to use the Mail-Ext Publisher plugin](https://wiki.jenkins.io/display/JENKINS/Convert+standard+mail+notifications+to+use+the+Mail-Ext+Publisher+plugin)
* etc
It also helps to detect plugin wiki-pages that have no redirections to [plugins.jenkins.io](https://plugins.jenkins.io/).

### Future work
It will be better to have all list of old wiki-plugin URLs rather than use [plugin-documentation-urls.json](https://updates.jenkins.io/current/plugin-documentation-urls.json) that has mixed up new and old URLs or with empty "*url*" value, `README.md`. (see `plugins_urls_list`).
If we try to parse again, but with `display/JENKINS/*+Plugin` regex - there will be found 506 plugins, that were not mentioned in the [plugin-documentation-urls.json](https://updates.jenkins.io/current/plugin-documentation-urls.json) or parsed badly.

**Comment by halkeye** [comment]
>     dump_file.write(str(pages_urls_dict))
Just FYI, thats not json (javascript object notation) it is PSON (python object notation)

You should change it to 
> import json
> json.dump(pages_urls_dict, dump_file)

**Comment by halkeye** [comment]
It would be awesome if you could detect something like https://wiki.jenkins.io/display/SECURITY/Jenkins+Security+Advisory+2012-03-05 which has "This page has been moved to https://jenkins.io/security/advisory/2012-03-05/" and we could build rewrite rules

**Comment by zbynek** [comment]
This gist is a snapshot of docs URLs before the major migration:
https://gist.github.com/zbynek/6f1fabb0e8ec46ca809e61e71b79340e

**Comment by halkeye** [comment]
I'm going to close this because I still don't know its purpose, it hasn't been updated in months, and in its current form outputting python objects instead of json it makes it hard to consume. Also, I don't really want to mix python and javascript in this repo, I think it should be a standalone script, or rewritten in javascript.

Anyone else feel free to open if you disagree
