### ISSUE TITLE
Ignore plugins that have reached end of life

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/jenkins-wiki-exporter#98]
Some plugins remain in the plugin catalog but have reached the end of their life.  Their final release has been made and usually directs the user to install a replacement plugin.

## Tombstone plugins

Some examples of those "tombstone" plugins include:

* [GitHub Organization Folder](https://plugins.jenkins.io/github-organization-folder/) - tombstone in 2017
* [CloudBees Free Enterprises](cloudbees-plugin-gateway) - tombstone in 2015

## Proposal

Could the two "tombstone" plugins be marked as "done" in the wiki exporter progress report so that no one attempts to migrate documentation for those plugins?

## Deprecated plugins

* [Warnings](https://plugins.jenkins.io/warnings/) - obsoleted by warnings-ng
* [Android Lint](https://plugins.jenkins.io/android-lint/) - warnings-ng says it replaces this plugin, but Android Lint does not appear to be deprecated  in its own documentation.  May need help from @orrc and @drulli resolving this one
* [CheckStyle](https://plugins.jenkins.io/checkstyle/)
* [Dry](https://plugins.jenkins.io/dry/)
* [FindBugs](https://plugins.jenkins.io/findbugs/)
* [PMD](https://plugins.jenkins.io/pmd/)
* [Static Analysis Utilities](https://plugins.jenkins.io/analysis-core/)
* [Static Analysis Collector](https://plugins.jenkins.io/analysis-collector/)

It seems that most of the derecated plugins are listed as "Done".

**Comment by halkeye** [comment]
Hard coded list? Let's use a different status like tombstoned?

**Comment by zbynek** [comment]
I think it's worth it to provide some documentation even for tombstoned plugins that says "Plugin X is deprecated because service Y is discontinued" or "Plugin X is now part of plugin Z". We can use the wiki-override mechanism of update-center2 so that no new release of those plugins is needed.

**Comment by halkeye** [comment]
I think we should have an official label for tombstone and deprecated, or maybe just archived?

```
# Type queries into this side of the screen, and you will 
# see intelligent typeaheads aware of the current GraphQL type schema, 
# live syntax, and validation errors highlighted within the text.

# We'll get you started with a simple query showing your username!
query { 
  viewer { 
    login
  }
  organization(login:"jenkinsci") {
    org: repository(name: "github-organization-folder-plugin") {
      labels(first:100){
        edges{
          node {
            name
          }
        }
      }
    }
    warnings:repository(name: "warnings-plugin") {
      labels(first:100){
        edges{
          node {
            name
          }
        }
      }
    }
  }
}
```

```
{
  "data": {
    "viewer": {
      "login": "halkeye"
    },
    "organization": {
      "org": {
        "labels": {
          "edges": [
            {
              "node": {
                "name": "bug"
              }
            },
            {
              "node": {
                "name": "duplicate"
              }
            },
            {
              "node": {
                "name": "enhancement"
              }
            },
            {
              "node": {
                "name": "help wanted"
              }
            },
            {
              "node": {
                "name": "invalid"
              }
            },
            {
              "node": {
                "name": "question"
              }
            },
            {
              "node": {
                "name": "wontfix"
              }
            },
            {
              "node": {
                "name": "work-in-progress"
              }
            }
          ]
        }
      },
      "warnings": {
        "labels": {
          "edges": [
            {
              "node": {
                "name": "dependencies"
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by oleg-nenashev** [comment]
@halkeye there is already an official GitHub topic for 'deprecated'

**Comment by halkeye** [comment]
> @halkeye there is already an official GitHub topic for 'deprecated'

right, totally knew that, helped you with the plugin site stuff

so final bit, I prefer labeling things as tombstoned (archived?)/depreciated (labeled?) instead of just marking them as done. But totally can mark them as done, or hide them entirely.

**Comment by orrc** [comment]
> Android Lint - warnings-ng says it replaces this plugin, but Android Lint does not appear to be deprecated in its own documentation

I've added the `deprecated` tag to the repo, and will update the docs.

**Comment by zbynek** [comment]
@orrc I created https://github.com/jenkins-infra/update-center2/pull/381 to make sure the plugin site reads android-lint docs from GH , so it's enough if you update the Readme in GitHub.

**Comment by MarkEWaite** [comment]
> so final bit, I prefer labeling things as tombstoned (archived?)/depreciated (labeled?) instead of just marking them as done. But totally can mark them as done, or hide them entirely.

I think that is a **much better** solution than my idea of marking them as "done".  If they are marked as "deprecated" or "archived" and still visible, readers will clearly understand that they have been considered and are intentionally not be converted from Wiki to GitHub based docs.

**Comment by halkeye** [comment]
![image](https://user-images.githubusercontent.com/110087/82870682-3ad5a200-9ee5-11ea-97f8-e17905a87d93.png)

**Comment by halkeye** [comment]
Not sold on the tombstoned name

**Comment by timja** [comment]
> Not sold on the tombstoned name

I think it doesn't need to be capitalised, it's too 'loud' TODO and OK are fine like that but not for a regular word I think

**Comment by zbynek** [comment]
Isn't "deprecated" better in this context? Tombstoned indicates that there is a tombstone release, which is not the case for all deprecated plugins.

**Comment by MarkEWaite** [comment]
I agree that "deprecated" is better than "tombstoned", particularly as noted by @zbynek that not all deprecated plugins have a tombstone release.  Some are deprecated for other reasons (dependent service offline, etc.)
